/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.voc.gradle.plugin;

import org.gradle.api.Project;
import org.gradle.api.Plugin;
import org.gradle.api.file.ConfigurableFileTree;
import org.gradle.api.model.ObjectFactory;

import javax.inject.Inject;

/**
 * A simple 'hello world' plugin.
 */
public class GradleDevtoolsPlugin implements Plugin<Project> {
    ConfigurableFileTree fileTree;

    @Inject
    public GradleDevtoolsPlugin(ObjectFactory objectFactory) {
        fileTree = objectFactory.fileTree();
    }

    public void apply(Project project) {
        fileTree.from("");
    }
}
